"""Initial database schema

Revision ID: 28cc21998ee0
Revises: 
Create Date: 2025-04-22 15:08:58.978267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.user import GUID


# revision identifiers, used by Alembic.
revision = '28cc21998ee0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('export_request',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('waybill_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('sender_email', sa.String(length=120), nullable=True),
    sa.Column('sender_address', sa.String(length=200), nullable=True),
    sa.Column('sender_business', sa.String(length=100), nullable=True),
    sa.Column('sender_mobile', sa.String(length=20), nullable=False),
    sa.Column('sender_signature', sa.Text(), nullable=True),
    sa.Column('receiver_name', sa.String(length=100), nullable=False),
    sa.Column('receiver_email', sa.String(length=120), nullable=True),
    sa.Column('receiver_address', sa.String(length=200), nullable=True),
    sa.Column('receiver_business', sa.String(length=100), nullable=True),
    sa.Column('receiver_mobile', sa.String(length=20), nullable=False),
    sa.Column('destination_address', sa.String(length=200), nullable=True),
    sa.Column('destination_country', sa.String(length=100), nullable=True),
    sa.Column('destination_postcode', sa.String(length=20), nullable=True),
    sa.Column('freight_pricing', sa.Float(), nullable=True),
    sa.Column('additional_charges', sa.Float(), nullable=True),
    sa.Column('pickup_charge', sa.Float(), nullable=True),
    sa.Column('handling_fees', sa.Float(), nullable=True),
    sa.Column('crating', sa.Float(), nullable=True),
    sa.Column('insurance_charge', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('is_collection', sa.Boolean(), nullable=True),
    sa.Column('customer_group', sa.String(length=100), nullable=True),
    sa.Column('order_booked_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_changed_by', GUID(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['status_changed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_request_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_request_status_changed_by'), ['status_changed_by'], unique=False)

    op.create_table('item_detail',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('export_request_id', GUID(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('image_file_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['export_request_id'], ['export_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_detail')
    with op.batch_alter_table('export_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_request_status_changed_by'))
        batch_op.drop_index(batch_op.f('ix_export_request_created_by'))

    op.drop_table('export_request')
    op.drop_table('user')
    # ### end Alembic commands ###
