"""add shipment status history table

Revision ID: 69889a00d896
Revises: 28cc21998ee0
Create Date: 2025-02-12 18:57:52.064598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69889a00d896'
down_revision = '28cc21998ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_status_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('shipment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['export_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_request', schema=None) as batch_op:
        batch_op.alter_column('status_changed_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='References the user who last changed the shipment status',
               existing_nullable=True)
        batch_op.alter_column('status_changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the shipment status was last changed',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        # Comment out the problematic index drop
        # batch_op.drop_index('idx_shipment_status_tracking')
        # Comment out the duplicate index creations
        # batch_op.create_index(batch_op.f('ix_export_request_created_by'), ['created_by'], unique=False)
        # batch_op.create_index(batch_op.f('ix_export_request_status_changed_by'), ['status_changed_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('export_request', schema=None) as batch_op:
        # Comment out the corresponding index drops
        # batch_op.drop_index(batch_op.f('ix_export_request_status_changed_by'))
        # batch_op.drop_index(batch_op.f('ix_export_request_created_by'))
        # Comment out the corresponding index creation in downgrade
        # batch_op.create_index('idx_shipment_status_tracking', ['status_changed_by', 'status_changed_at'], unique=False)
        batch_op.alter_column('status_changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the shipment status was last changed',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status_changed_by',
               existing_type=sa.UUID(),
               comment='References the user who last changed the shipment status',
               existing_nullable=True)

    op.drop_table('shipment_status_history')
    # ### end Alembic commands ###
